server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:service1.jks
    key-store-password: changeit
    key-alias: service1
    protocol: TLS
    enabled-protocols: 
      - TLSv1.2
      - TLSv1.3

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
