server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:service1.jks
    key-store-password: changeit
    key-alias: ${KEY_ALIAS:service1}
    protocol: TLS
    enabled-protocols:
      - TLSv1.2
      - TLSv1.3

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: s1
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        preferIpAddress: true
        serviceName: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s
        health-check-tls-skip-verify: true
        scheme: https
